apiVersion: v2
name: argocd-image-updater
description: Argo CD Image Updater
type: application

version: 0.1.0

dependencies:
  - name: argocd-image-updater
    version: 0.13.0
    repository: https://argoproj.github.io/argo-helm