apiVersion: v2
name: kube-prometheus-stack
description: Monitoring stack
type: application

version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "79.x.x"
    repository: https://prometheus-community.github.io/helm-charts