grafana:
  adminPassword: admin123

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: alb

    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: platform-dev
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.order: "20"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:239713807106:certificate/0a7966b8-6f0f-449a-9e6c-e97e54cce30b
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"

    hosts:
      - grafana-dev.space9.in

    path: /
    pathType: Prefix

prometheus:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: alb

    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: platform-dev
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.order: "30"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:239713807106:certificate/0a7966b8-6f0f-449a-9e6c-e97e54cce30b
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"

    hosts:
      - prometheus-dev.space9.in

    paths:
      - /
    pathType: Prefix

alertmanager:
  enabled: false

defaultRules:
  create: true