grafana:
  adminPassword: admin123

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: alb

    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: platform-dev
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.order: "20"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:074095961179:certificate/14e3568e-0172-4c56-a63f-4f239cddb696
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"

    hosts:
      - grafana-dev.space9.in

    path: /
    pathType: Prefix

prometheus:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: alb

    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: platform-dev
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.order: "30"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:074095961179:certificate/14e3568e-0172-4c56-a63f-4f239cddb696
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"

    hosts:
      - prometheus-dev.space9.in

    paths:
      - /
    pathType: Prefix

alertmanager:
  enabled: false

defaultRules:
  create: true