apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "python-backend.fullname" . }}
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "python-backend.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "python-backend.name" . }}

    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: {{ include "python-backend.fullname" . }}

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "python-backend.fullname" . }}
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "python-backend.fullname" . }}
                  key: DB_PASSWORD

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3